### ISSUE TITLE
implement add-on storage + submission for demographic survey

### ISSUE THREAD

**Issue by hamilton** [mozilla-ion/ion-core-addon#124]
TO finish the onboarding flow implementation, we'll need to submit the demographic survey data provided by the user.

1. The current schema is embedded [in the demographic page survey](https://github.com/mozilla-ion/ion-core-addon/blob/master/src/routes/demographics/Content.svelte#L57). I am guessing it will need to be removed from here and made into a separate json file so we can use it elsewhere.
2. we'll need to add store functions in `create-store.js`, `web-extension.js`, and the background scripts.

**Comment by Dexterp37** [comment]
@knowtheory to power the questions outlined [in this document - a very early proposal -](https://docs.google.com/document/d/1ATMipr4BgpRKR9clD4gLKh-17SJ2DnwMpftygpjKLkU/edit#heading=h.dtq31symiun0), I believe we need to send the demographics data both to the `pioneer-meta` table (for general statistics about the Ion panel, to which study authors don't have access) and to the specific study tables (to which study authors have access). Is this correct?

**Comment by knowtheory** [comment]
Okay, yeah, this is a mix of product and engineering concerns.

I made some assumptions in my head, so we definitely should check with @acmiyaguchi & @mreid-moz about direction, preferences & feasibility:

1. Data goes into `pioneer-meta`, data is batched periodically and made accessible in study environments somehow?
2. What you're suggesting.  Data goes into both `pioneer-meta` and a user table.

The things I'm thinking about is how tightly synced the data is (in terms of inserts and deletes).

**Comment by Dexterp37** [comment]
>     1. Data goes into `pioneer-meta`, data is batched periodically and made accessible in study environments somehow?

It has the same behaviour it would have in the specific study table. The main differences:

- not restricted to users of a specific study;
- the subset of people with access to `pioneer-meta` (this would be a restricted group within Mozilla) is different than the subset of people who have access to the study data (study authors);
- it would contain historical data for a set of ids (while the data in the study table would only contain the data for the specific period of time of the study);

>     2. What you're suggesting.  Data goes into both `pioneer-meta` and a user table.

I'm suggesting to send data both to the `pioneer-meta` (Mozilla-only access) and to the specific study table (study authors only access). This would allow:

- perform any time-based analysis on the whole panel of people;
- compare the platform panel vs a specific study panel;
- allow study authors to understand the characteristics of their panel.

This is mostly about analysis requirements. The technical constraints are the same, I think!

The other option would be to only send the data to either only the `pioneer-meta` or the study table:

- by sending exclusively to `pioneer-meta` (Mozilla-only access), if study authors want to understand the composition of the panel, we'd need to create and send a report about that;
- by sending exclusively to the specific study table (Authors-only access), if we want to understand the composition of the panel, we'd need access to the whole study table.

**Comment by acmiyaguchi** [comment]
I'm a bit unclear on some of the requirements. In the case of the enrollment, there is a difference between enrollment in the overall program vs enrollment in a specific study. Conversely, there is a difference between a deletion request in a specific study vs deletion from the program.

I'd say (2) is the most straightforward to implement since we already have study-specific tables. (1) is technically possible, but it would require setting up authorized views per study through the shared project where we take the inner join of study enrollments against the meta demographic table. We currently treat the pioneer-meta project as an isolated study, and I have concerns in joining data across studies. I'd have to take a closer look at the deletion-request behavior in this case though, since I believe the enrollment table is not subject to our data deletion requests.

**Comment by Dexterp37** [comment]
> 
> 
> I'm a bit unclear on some of the requirements. In the case of the enrollment, there is a difference between enrollment in the overall program vs enrollment in a specific study. Conversely, there is a difference between a deletion request in a specific study vs deletion from the program.

@acmiyaguchi for the data specifically discussed in this issue, we're talking about the results of the survey that will be sent right after joining the platform: it won't always be sent, it may contain partial data, but it's important for both study authors and us to get an understanding of the panel for the whole platform and specific studies

**Comment by knowtheory** [comment]
Okay, I had assumed that we would send the survey as a ping that went into a table space which only the Rally team has access to (i am happy to have this assumption invalidated, if possible).

Separately from the primary ownership of the survey data, we need to specify a way to expose a subset of survey data configured on a per study environment basis (subset in terms of population relative to who the enrolled users are, and then studies can ask for a subset of the data fields in the user survey responses).

The reason I had assumed that we would implement this on the server side, rather than at study enrollment time was because studies don't necessarily need all of the data fields collected in the survey, and we'd like to encourage partners to minimize the data they are requesting access to.

So, @Dexterp37 if you can think of a way that we can enforce sending a subset of survey fields via a ping structure, then that that still seems viable.  Otherwise, I think we should specify the requirements on the serverside more clearly.

**Comment by Dexterp37** [comment]
> 
> 
> Okay, I had assumed that we would send the survey as a ping that went into a table space which only the Rally team has access to (i am happy to have this assumption invalidated, if possible).

No need to invalidate it :-) Let's start by exclusively sending data to the Rally team table.

> Separately from the primary ownership of the survey data, we need to specify a way to expose a subset of survey data configured on a per study environment basis (subset in terms of population relative to who the enrolled users are, and then studies can ask for a subset of the data fields in the user survey responses).
> 
> The reason I had assumed that we would implement this on the server side, rather than at study enrollment time was because studies don't necessarily need all of the data fields collected in the survey, and we'd like to encourage partners to minimize the data they are requesting access to.

Cool, sounds like we need to specify this a bit more. Doing it "server-side" (post-ingestion) means we need to either have a manual process for doing it, or building some way to automate that.

> So, @Dexterp37 if you can think of a way that we can enforce sending a subset of survey fields via a ping structure, then that that still seems viable. Otherwise, I think we should specify the requirements on the serverside more clearly.

I believe we could provide this capability through `rally.js`: at initialization, studies can define what they care about, and we could send the data on their behalf automatically, to their table.

This should be tackled separately from this issue and the related PR: this is material for the partner support library proposal.

**Comment by Dexterp37** [comment]
Note that this is currently blocked by the decision on [this document](https://docs.google.com/document/d/1_DNHPmFOdfPg_PLleenur185mcgVKUH8EGp4V-UeJZk/edit?ts=5faec577#heading=h.561oygfk6bnm). Specifically, this blocks progress on #139

**Comment by knowtheory** [comment]
> Note that this is currently blocked by the decision on [this document](https://docs.google.com/document/d/1_DNHPmFOdfPg_PLleenur185mcgVKUH8EGp4V-UeJZk/edit?ts=5faec577#heading=h.561oygfk6bnm). Specifically, this blocks progress on #139

Hey, checked in on the recommendation in this doc.  Option 4 looks good.  Let's go for that.

Thank you & Anthony for pulling together the docs around this.

**Comment by Dexterp37** [comment]
Thanks @knowtheory . The bug for tracking key deployment is [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1677761)

**Comment by Dexterp37** [comment]
This is now unblocked. New keys were deployed in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1677761).
