### ISSUE TITLE
Add the MPL license header to all the relevant files in this repo

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-ion/ion-core-addon#136]
For javascript files, this is the expected format:

```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
```

**Comment by pdehaan** [comment]
I tried a couple ESLint modules which could check/autofix this, but I don't think I got either working 100%:

- https://github.com/redradix/eslint-plugin-copyright/
- https://github.com/nickdeis/eslint-plugin-notice/

Both seemed like good options, but I think I found a few cases where random .svelte files would not get the copyright header added or report it as missing.

I also cobbled together this hacky Git command, but might not be 100% accurate since I think some .svelte files are basically .svg files which might not need copyright headers (or perhaps differently formatted copyright headers):

```sh
git grep -L "This Source Code Form" | grep -E "\.(svelte|js)$"
```
