### ISSUE TITLE
cancelling study add-on install still shows study add-on as installed

### ISSUE THREAD

**Issue by rhelmer** [mozilla-ion/ion-core-addon#81]
I noticed that if I cancel extension install of a study add-on, then the core add-on `moz-extension://` control panel page shows the study as enrolled even though the study add-on is not actually installed. It still persists even after browser restart.

@hamilton @Dexterp37 Conceptually I think on startup the Ion Core should get a list of all add-ons on startup, and it should listen to add-on un/install and enable/disable events to update its internal state. It's ok to cache this state but we should make sure it does not get stale.

**Comment by rhelmer** [comment]
Specifically this is the prompt that I clicked "Cancel" on 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/61412/96284005-db5e5880-0f91-11eb-82ef-65e940a053df.png">

**Comment by Dexterp37** [comment]
> @hamilton @Dexterp37 Conceptually I think on startup the Ion Core should get a list of all add-ons on startup, and it should listen to add-on un/install and enable/disable events to update its internal state. It's ok to cache this state but we should make sure it does not get stale.

Yes, I agree with you. I think we briefly touched this before but one potential solution could be to create a [`connection-based channel`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Connection-based_messaging) between the UI and the background script (instead of just sending simple one spot messages) to listen for updates (the core addon always has the correct state because it listens to install/uninstall events).

This has implications for enrollment pings too: we don't want to send the ping when we trigger the installation, but rather when we hear that the addon was installed.
